spring:
  application:
    name: spring-app

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health
    jmx:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

context:
  initializer:
    classes: io.github.carlomicieli.BeansInitializer